export const DASHBOARD_COPY_EN = {
  common: {
    notSet: "Not set",
    search: "Search",
    loading: "Loading...",
    optional: "optional",
    searchPlaceholder: "Search...",
    signOutSuccess: "Signed out successfully",
    cropOptions: {
      wheat: "Wheat",
      rice: "Rice",
      maize: "Maize",
      cotton: "Cotton",
      sugarcane: "Sugarcane",
      potato: "Potato",
      tomato: "Tomato",
      onion: "Onion",
      soybean: "Soybean",
      groundnut: "Groundnut",
      mustard: "Mustard",
      pulses: "Pulses",
      vegetables: "Vegetables",
      fruits: "Fruits",
      coffee: "Coffee",
      tea: "Tea",
      cocoa: "Cocoa",
      cassava: "Cassava",
      kaukau: "Kaukau (Sweet Potato)",
      taro: "Taro",
      millet: "Millet",
      sorghum: "Sorghum",
      other: "Other",
    },
    soilTypes: {
      clay: "Clay",
      sandy: "Sandy",
      loamy: "Loamy",
      silty: "Silty",
      peaty: "Peaty",
      chalky: "Chalky",
      blackSoil: "Black Soil",
      redSoil: "Red Soil",
      alluvialSoil: "Alluvial Soil",
      alluvial: "Alluvial",
    },
    growthStages: {
      seedling: "Seedling",
      vegetative: "Vegetative",
      flowering: "Flowering",
      fruiting: "Fruiting/Grain filling",
      maturity: "Maturity",
    },
    seasons: {
      kharif: "Kharif (Monsoon)",
      rabi: "Rabi (Winter)",
      zaid: "Zaid (Summer)",
    },
    eventTypes: {
      fertilizer: "Fertilizer",
      spraying: "Spraying",
      irrigation: "Irrigation",
      harvest: "Harvest",
      sowing: "Sowing",
      general: "General",
    },
    priorities: {
      low: "Low",
      medium: "Medium",
      high: "High",
    },
    listingTypes: {
      all: "All Types",
      sell: "For Sale",
      buy: "Buy Requests",
      selling: "Selling",
      buying: "Buying",
      sold: "Sold",
    },
    units: {
      kg: "Kg",
      quintal: "Quintal",
      ton: "Ton",
      bag: "Bag",
      crate: "Crate",
    },
  },
  sidebar: {
    dashboard: "Dashboard",
    cropAdvisor: "Crop Advisor",
    weather: "Weather",
    soilAnalysis: "Soil Analysis",
    diseaseScanner: "Leaf & Disease Scanner",
    irrigation: "Irrigation",
    fertilizer: "Fertilizer",
    farmCalendar: "Farm Calendar",
    marketplace: "Marketplace",
    aiAssistant: "AI Assistant",
    settings: "Settings",
    help: "Help",
    freePlan: "Free Plan",
    premiumTitle: "Go Premium",
    premiumDescription: "Unlock all AI features & expert chat",
    premiumPrice: "₹99/month",
    premiumButton: "Upgrade Now",
    signOut: "Sign Out",
    openMenu: "Open menu",
  },
  header: {
    searchPlaceholder: "Search...",
  },
  languageSelector: {
    button: "Select Country & Language",
    title: "Select Your Country & Language",
    searchPlaceholder: "Search country or language...",
    stepCountry: "1. Select your country",
    stepLanguage: "2. Select language for {country}",
    selectedLabel: "Selected:",
    summary: "All AI responses and agricultural terms will be in {language}",
    confirm: "Confirm Language",
  },
  dashboard: {
    title: "Dashboard",
    subtitle: "Welcome! Here's your agricultural command center.",
    bannerTitle: "🌍 Set your country & language",
    bannerSubtitle: "All AI features will respond in your selected language",
    stats: {
      marketplace: "Marketplace",
      activeListings: "Active listings",
      weather: "Weather",
      searchLocation: "Search a location",
      language: "Language",
      aiFeatures: "AI Features",
      allActive: "All active",
    },
    weatherCard: {
      title: "Today's Weather",
      humidity: "Humidity",
      wind: "Wind",
      feelsLike: "Feels Like",
      loading: "Loading weather...",
      viewForecast: "View Full Forecast",
    },
    recommendations: {
      title: "AI Recommendations",
      soil: "🧪 Soil Analysis — Upload a soil photo to get nutrient levels and crop recommendations.",
      disease: "🍃 Disease Scanner — Take a photo of any crop leaf to identify diseases and get treatment plans.",
      assistant: "🤖 AI Assistant — Ask any farming question in your own language and get expert advice.",
      chatButton: "Chat with AI Assistant",
    },
    quickActionsTitle: "Quick Actions",
    quickActions: {
      cropAdvisor: { label: "Crop Advisor", desc: "Get crop recommendations" },
      weather: { label: "Weather", desc: "Real-time forecasts" },
      soilAnalysis: { label: "Soil Analysis", desc: "Photo-based testing" },
      diseaseScanner: { label: "Disease Scanner", desc: "Leaf & disease detection" },
      irrigation: { label: "Irrigation", desc: "Smart water management" },
      fertilizer: { label: "Fertilizer", desc: "Nutrient planning" },
      farmCalendar: { label: "Farm Calendar", desc: "Schedule activities" },
      marketplace: { label: "Marketplace", desc: "Buy & sell produce" },
      aiAssistant: { label: "AI Assistant", desc: "Ask anything" },
    },
  },
  cropAdvisor: {
    title: "Crop Advisor",
    subtitle: "Get AI-powered crop recommendations based on your farm conditions",
    cardTitle: "Tell us about your farm",
    labels: {
      location: "Location / Region *",
      soilType: "Soil Type *",
      season: "Planting Season *",
      farmSize: "Farm Size (optional)",
      yield: "Yield:",
      profit: "Profit:",
      duration: "Duration:",
      water: "Water:",
      sow: "Sow:",
    },
    placeholders: {
      location: "e.g., Punjab, Maharashtra",
      soilType: "Select soil type",
      season: "Select season",
      farmSize: "e.g., 5 hectares",
    },
    buttons: {
      loading: "Getting AI Recommendations...",
      submit: "Get AI Recommendations",
      viewPlan: "View Full Plan",
    },
    loading: {
      title: "Analyzing your farm conditions...",
      subtitle: "Our AI is finding the best crops for you",
    },
    resultsTitle: "AI-Recommended Crops for Your Farm",
    suitabilityMatch: "{value}% match",
    empty: "Enter your farm details above to get personalized crop recommendations",
    errors: {
      missingTitle: "Missing Information",
      missingDescription: "Please fill in location, soil type, and season.",
      failedTitle: "Failed to Get Recommendations",
      tryAgain: "Please try again.",
    },
  },
  weather: {
    title: "Weather Intelligence",
    subtitle: "Real-time weather for any village, town or city worldwide",
    searchPlaceholder: "Search any place — village, town, city (e.g., Kibera, Nairobi)",
    getWeather: "Get Weather",
    myLocation: "My Location",
    loading: {
      title: "Fetching live weather data...",
      subtitle: "Generating AI farming insights",
    },
    empty: {
      title: "Search any location worldwide",
      subtitle: "Get real-time weather for any village, town, or city. Type to search — our system covers every corner of the earth.",
      recentSearches: "Recent Searches",
      pngProvinces: "Papua New Guinea Provinces",
      popularLocations: "Popular Locations",
    },
    currentWeather: "Current Weather",
    humidity: "Humidity",
    wind: "Wind",
    feelsLike: "Feels Like",
    mapTitle: "Farm Location Map",
    mapFrameTitle: "Farm location map",
    alertsTitle: "AI Farming Alerts",
    noAlerts: "No specific alerts for your area today.",
    forecastTitle: "7-Day Forecast",
    farmingTitle: "Smart Farming Recommendations",
    statusLabels: {
      doNow: "Do Now",
      skip: "Skip",
      good: "Good",
      wait: "Wait",
    },
    errors: {
      geolocationNotSupported: "Geolocation not supported",
      failedCurrentLocation: "Failed to get weather for your location",
      locationDenied: "Location access denied",
      locationDeniedDescription: "Please enable location access or search manually",
      enterLocation: "Please enter a location",
      fetchFailed: "Weather Fetch Failed",
      tryAgain: "Please try again.",
    },
  },
  soilAnalysis: {
    title: "Soil Analysis",
    subtitle: "Upload a soil photo for AI-powered nutrient and crop analysis",
    uploadTitle: "Capture Soil Sample",
    uploadPrompt: "Take a photo or upload soil image",
    uploadHint: "JPG, PNG, WEBP (max 10MB)",
    labels: {
      location: "Location (optional)",
      crops: "Current/Planned Crops (optional)",
      healthScore: "Soil Health Score",
      soilType: "Soil Type",
      texture: "Texture",
      moisture: "Moisture",
      organicMatter: "Organic Matter",
      phEstimate: "pH Estimate",
      color: "Color",
      nutrientAnalysis: "Nutrient Analysis",
      enrichmentPlan: "Soil Enrichment Plan",
      bestCrops: "Best Crops for This Soil",
      warnings: "Warnings",
      improvements: "Improvement Steps",
      match: "{value}% Match",
    },
    placeholders: {
      location: "e.g., Ludhiana, Punjab",
      crops: "e.g., Wheat, Rice",
    },
    buttons: {
      loading: "Analyzing Soil...",
      submit: "Analyze Soil",
    },
    resultTitle: "Soil Analysis Report",
    empty: "Upload a soil photo to get detailed nutrient analysis",
    loading: "Analyzing soil composition...",
    errors: {
      fileTooLarge: "File too large",
      fileTooLargeDescription: "Max 10MB",
      failedTitle: "Analysis Failed",
      tryAgain: "Please try again",
    },
  },
  diseaseScanner: {
    title: "Leaf & Disease Scanner",
    subtitle: "Identify crops, detect diseases, and get treatment recommendations",
    uploadTitle: "Scan Crop Leaf",
    uploadPrompt: "Take a photo of the leaf or crop",
    uploadHint: "JPG, PNG, WEBP (max 10MB)",
    labels: {
      cropType: "Crop Type (optional)",
      symptomsLabel: "Describe Symptoms (optional)",
      cropIdentified: "Crop Identified",
      diagnosis: "Diagnosis",
      causedBy: "Caused by",
      spreadsVia: "Spreads via",
      affects: "Affects",
      progression: "Progression",
      symptoms: "Symptoms",
      immediateAction: "Immediate Action",
      chemicalTreatment: "Chemical Treatment",
      organicTreatment: "Organic Treatment",
      cropInformation: "Crop Information",
      conditions: "Conditions",
      water: "Water",
      nutrients: "Nutrients",
      commonPests: "Common Pests",
      companionPlants: "Companion Plants",
      harvestSigns: "Harvest Signs",
      prevention: "Prevention",
      expertConsultation: "Expert Consultation Recommended",
      familyStage: "Family: {family} · Stage: {stage}",
      active: "Active",
      dosage: "Dosage",
      frequency: "Frequency",
      method: "Method",
      wait: "Wait",
    },
    placeholders: {
      cropType: "e.g., Tomato, Rice, Wheat",
      symptoms: "e.g., Yellow spots on leaves",
    },
    buttons: {
      loading: "Analyzing...",
      submit: "Analyze Crop",
    },
    resultTitle: "Complete Analysis",
    empty: "Upload an image for complete crop & disease analysis",
    loading: "AI is analyzing your crop...",
    errors: {
      fileTooLarge: "File too large",
      fileTooLargeDescription: "Max 10MB",
      failedTitle: "Analysis Failed",
      tryAgain: "Try again",
    },
  },
  irrigation: {
    title: "Smart Irrigation",
    subtitle: "AI-optimized water management for your crops",
    cardTitle: "Generate Your Irrigation Plan",
    labels: {
      cropType: "Crop Type *",
      growthStage: "Growth Stage *",
      fieldSize: "Field Size (ha)",
      soilType: "Soil Type",
      location: "Location",
      dailyNeed: "Daily Need",
      perHectare: "per hectare",
      weeklySavings: "Weekly Savings",
      saved: "₹{value} saved",
      soilMoisture: "Soil Moisture",
      target: "Target: {min}-{max}%",
      efficiency: "Efficiency",
      currentLevel: "Current level",
      optimal: "Optimal: {min}-{max}% for {crop}",
      recommendedMethod: "Recommended Method",
      proTips: "Pro Tips",
      schedule: "Smart Irrigation Schedule",
      waterUsage: "water usage",
      savingWater: "Saving water!",
      rainExpected: "Rain expected - skip irrigation",
    },
    placeholders: {
      cropType: "Select crop",
      growthStage: "Select stage",
      fieldSize: "5",
      soilType: "Optional",
      location: "e.g., Punjab",
    },
    buttons: {
      loading: "Generating Plan...",
      submit: "Get AI Irrigation Plan",
    },
    loading: {
      title: "Analyzing weather & crop data...",
      subtitle: "Creating your personalized irrigation schedule",
    },
    empty: "Select your crop and growth stage to get an AI-powered irrigation schedule",
    errors: {
      missingTitle: "Please select crop type and growth stage",
      failedTitle: "Failed to get irrigation plan",
      tryAgain: "Please try again.",
    },
  },
  fertilizer: {
    title: "Fertilizer Planner",
    subtitle: "AI-optimized nutrient management for maximum yield",
    cardTitle: "Generate AI Fertilizer Plan",
    labels: {
      cropType: "Crop Type *",
      growthStage: "Growth Stage *",
      soilType: "Soil Type",
      fieldSize: "Field Size (ha)",
      location: "Location",
      estimatedCost: "Estimated Total Cost",
      forHectares: "For {size} hectares",
      yieldBoost: "Expected Yield Boost",
      yieldBoostComparison: "vs standard fertilization",
      cautions: "Cautions",
      organicAlternatives: "Organic Alternatives",
      recommendations: "AI Fertilizer Recommendations",
      applicationSchedule: "Application Schedule",
      current: "Current",
      optimal: "Optimal: {value}%",
      quantity: "Quantity",
      costPerHectare: "Cost/hectare",
      timing: "Timing",
      method: "Method",
      applyNow: "Apply Now",
      highPriority: "High Priority",
      medium: "Medium",
      low: "Low",
    },
    placeholders: {
      cropType: "Select crop",
      growthStage: "Select stage",
      soilType: "Optional",
      fieldSize: "5",
      location: "e.g., Maharashtra",
    },
    buttons: {
      loading: "Generating Plan...",
      submit: "Get AI Fertilizer Plan",
    },
    loading: {
      title: "Analyzing soil & crop data...",
      subtitle: "Creating your personalized fertilizer plan",
    },
    empty: "Select your crop and growth stage to get an AI-powered fertilizer plan",
    errors: {
      missingTitle: "Please select crop type and growth stage",
      failedTitle: "Failed to get fertilizer plan",
      tryAgain: "Please try again.",
    },
  },
  farmCalendar: {
    title: "Farm Calendar",
    subtitle: "Track your farming activities and never miss a deadline",
    urgentTasks: "Urgent Tasks ({count})",
    totalEvents: "Total Events",
    completed: "Completed",
    upcoming: "Upcoming",
    urgent: "Urgent",
    addEvent: "Add Event",
    addFarmEvent: "Add Farm Event",
    labels: {
      title: "Title *",
      type: "Type",
      priority: "Priority",
      crop: "Crop",
      plot: "Plot",
      eventDate: "Event Date *",
      description: "Description",
      filterPlaceholder: "Filter by type",
      completedPast: "Completed / Past",
      overdue: "Overdue",
    },
    placeholders: {
      title: "e.g., Apply urea to wheat plot",
      crop: "e.g., Wheat",
      plot: "e.g., North Field",
      description: "Additional notes...",
    },
    buttons: {
      submit: "Add Event",
    },
    empty: "No events yet. Add your first farming activity!",
    useTemplate: "Use Template",
    errors: {
      failedLoad: "Failed to load events",
      failedAdd: "Failed to add event",
      added: "Event added! 🌱",
      deleted: "Event deleted",
    },
    templates: {
      button: "Crop Templates",
      dialogTitle: "Crop Lifecycle Templates",
      reviewTitle: "Review: {name}",
      back: "Back",
      intro: "Pick a crop cycle. You'll review and edit each task (date, type, priority, notes) before saving.",
      editIntro: "Adjust dates, edit details, or remove tasks. Uncheck a task to skip it without deleting.",
      tasksCount: "{count} tasks • ~{days} days",
      irrigationBadge: "💧 {count} irrigation",
      fertilizerBadge: "🧪 {count} fertilizer",
      sprayingBadge: "🐛 {count} spraying",
      harvestBadge: "🌾 {count} harvest",
      startDate: "Start Date",
      plotOptional: "Plot (optional)",
      plotPlaceholder: "e.g. North field",
      proceed: "Review & edit {count} tasks →",
      selectionSummary: "{selected} of {total} tasks selected",
      selectAll: "All",
      selectNone: "None",
      taskDate: "Date",
      taskType: "Type",
      taskPriority: "Priority",
      removeTask: "Remove task",
      saving: "Saving...",
      saveTasks: "Save {count} tasks",
      noTasksSelected: "No tasks selected",
      failedApply: "Failed to apply template",
      appliedSuccess: "{name} applied — {count} events created!",
      cropNames: {
        kaukau: "Kaukau (Sweet Potato) Cycle",
        taro: "Taro Growing Cycle",
        rice: "Rice Paddy Cycle",
        maize: "Maize/Corn Cycle",
      },
    },
  },
  marketplace: {
    title: "Marketplace",
    subtitle: "Buy and sell farm produce — connect with farmers and buyers",
    stats: {
      activeListings: "Active Listings",
      forSale: "For Sale",
      buyRequests: "Buy Requests",
      myListings: "My Listings",
    },
    tabs: {
      browse: "Browse All",
      my: "My Listings",
    },
    createListing: "Create Listing",
    newListing: "New Listing",
    labels: {
      listingType: "Listing Type",
      title: "Title *",
      cropType: "Crop Type *",
      quantity: "Quantity *",
      unit: "Unit",
      pricePerUnit: "Price/Unit *",
      location: "Location",
      contactPhone: "Contact Phone",
      description: "Description",
      crop: "Crop:",
      qty: "Qty:",
      price: "Price:",
      enterName: "Enter your name to start chatting",
    },
    placeholders: {
      title: "e.g., Fresh organic wheat - 50 quintal",
      cropType: "Select crop",
      quantity: "50",
      pricePerUnit: "2500",
      location: "e.g., Nairobi, Kenya",
      contactPhone: "+254 7XX XXX XXX",
      description: "Quality details, delivery info...",
      search: "Search crops, locations...",
      chatName: "Your name",
      chatMessage: "Type a message...",
      setNameFirst: "Set your name first...",
    },
    options: {
      sell: "I want to Sell",
      buy: "I want to Buy",
    },
    buttons: {
      loading: "Creating...",
      submit: "Create Listing",
      chat: "Chat",
      sold: "Sold",
      delete: "Delete",
      createFirst: "Create First Listing",
      setName: "Set",
    },
    chatTitle: "Chat",
    emptyBrowse: "No listings found.",
    emptyMine: "You haven't created any listings yet.",
    noMessages: "No messages yet. Start the conversation!",
    errors: {
      fillRequired: "Please fill all required fields",
      failedCreate: "Failed to create listing",
      created: "Listing created! 🛒",
      markedSold: "Marked as sold! ✅",
      deleted: "Listing deleted",
      enterNameFirst: "Please enter your name first",
      failedSend: "Failed to send message",
    },
  },
  aiAssistant: {
    title: "AI Agricultural Assistant",
    subtitle: "Speaking in {language}",
    welcome: "Welcome! 🌾 I'm your AI Agricultural Assistant.\n\n🌍 **Country**: {country}\n🗣️ **Response language**: {language}\n🎙️ **Voice input locale**: {voiceLocale}\n\nAsk about crops, pests, irrigation, soil health, fertilizer, weather, or farm markets.",
    repliesIn: "Replies in",
    voiceLocale: "Voice locale",
    thinking: "Thinking...",
    listening: "Listening in {language}...",
    askPlaceholder: "Ask your farming question in {language}...",
    tapQuestion: "Tap a farming question to ask instantly",
    voiceInputError: "Voice input error",
    aiError: "AI Error",
    failedConnect: "Failed to connect to AI",
    noBody: "No AI response body received",
    failedResponse: "Failed to get response",
  },
  settings: {
    title: "Settings",
    subtitle: "Manage your profile and preferences",
    personalInformation: "Personal Information",
    farmDetails: "Farm Details",
    labels: {
      fullName: "Full Name",
      phone: "Phone",
      email: "Email",
      language: "Language",
      location: "Location / Region",
      farmSize: "Farm Size",
      soilType: "Soil Type",
      primaryCrop: "Primary Crop",
      whyFill: "Why fill this out?",
      whyFillDescription: "Your farm details are used to personalize AI recommendations across all modules — weather alerts, crop advice, irrigation schedules, and fertilizer plans will be tailored to your specific conditions.",
      weatherUsage: "Used for weather data and crop recommendations",
    },
    placeholders: {
      fullName: "Your name",
      phone: "+91 XXXXX XXXXX",
      location: "e.g., Ludhiana, Punjab",
      farmSize: "e.g., 5 hectares",
      soilType: "Select soil type",
      primaryCrop: "e.g., Wheat, Rice",
    },
    buttons: {
      loading: "Saving...",
      submit: "Save Profile",
    },
    errors: {
      failedSave: "Failed to save profile",
      saved: "Profile updated! ✅",
    },
  },
} as const;

export type DashboardCopy = typeof DASHBOARD_COPY_EN;
