// Complete list of 195 countries with their primary languages
export interface CountryLanguage {
  country: string;
  languages: string[];
  code: string; // ISO country code
}

export const COUNTRY_LANGUAGES: CountryLanguage[] = [
  { country: "Afghanistan", languages: ["Pashto", "Dari"], code: "AF" },
  { country: "Albania", languages: ["Albanian"], code: "AL" },
  { country: "Algeria", languages: ["Arabic"], code: "DZ" },
  { country: "Andorra", languages: ["Catalan"], code: "AD" },
  { country: "Angola", languages: ["Portuguese"], code: "AO" },
  { country: "Antigua and Barbuda", languages: ["English"], code: "AG" },
  { country: "Argentina", languages: ["Spanish"], code: "AR" },
  { country: "Armenia", languages: ["Armenian"], code: "AM" },
  { country: "Australia", languages: ["English"], code: "AU" },
  { country: "Austria", languages: ["German"], code: "AT" },
  { country: "Azerbaijan", languages: ["Azerbaijani"], code: "AZ" },
  { country: "Bahamas", languages: ["English"], code: "BS" },
  { country: "Bahrain", languages: ["Arabic"], code: "BH" },
  { country: "Bangladesh", languages: ["Bengali"], code: "BD" },
  { country: "Barbados", languages: ["English"], code: "BB" },
  { country: "Belarus", languages: ["Belarusian", "Russian"], code: "BY" },
  { country: "Belgium", languages: ["Dutch", "French", "German"], code: "BE" },
  { country: "Belize", languages: ["English"], code: "BZ" },
  { country: "Benin", languages: ["French"], code: "BJ" },
  { country: "Bhutan", languages: ["Dzongkha"], code: "BT" },
  { country: "Bolivia", languages: ["Spanish"], code: "BO" },
  { country: "Bosnia and Herzegovina", languages: ["Bosnian", "Croatian", "Serbian"], code: "BA" },
  { country: "Botswana", languages: ["English"], code: "BW" },
  { country: "Brazil", languages: ["Portuguese"], code: "BR" },
  { country: "Brunei", languages: ["Malay"], code: "BN" },
  { country: "Bulgaria", languages: ["Bulgarian"], code: "BG" },
  { country: "Burkina Faso", languages: ["French"], code: "BF" },
  { country: "Burundi", languages: ["Kirundi", "French"], code: "BI" },
  { country: "Cabo Verde", languages: ["Portuguese"], code: "CV" },
  { country: "Cambodia", languages: ["Khmer"], code: "KH" },
  { country: "Cameroon", languages: ["French", "English"], code: "CM" },
  { country: "Canada", languages: ["English", "French"], code: "CA" },
  { country: "Central African Republic", languages: ["French", "Sango"], code: "CF" },
  { country: "Chad", languages: ["French", "Arabic"], code: "TD" },
  { country: "Chile", languages: ["Spanish"], code: "CL" },
  { country: "China", languages: ["Mandarin Chinese"], code: "CN" },
  { country: "Colombia", languages: ["Spanish"], code: "CO" },
  { country: "Comoros", languages: ["Arabic", "French", "Comorian"], code: "KM" },
  { country: "Congo (Congo-Brazzaville)", languages: ["French"], code: "CG" },
  { country: "Democratic Republic of the Congo", languages: ["French"], code: "CD" },
  { country: "Costa Rica", languages: ["Spanish"], code: "CR" },
  { country: "Côte d'Ivoire", languages: ["French"], code: "CI" },
  { country: "Croatia", languages: ["Croatian"], code: "HR" },
  { country: "Cuba", languages: ["Spanish"], code: "CU" },
  { country: "Cyprus", languages: ["Greek", "Turkish"], code: "CY" },
  { country: "Czech Republic", languages: ["Czech"], code: "CZ" },
  { country: "Denmark", languages: ["Danish"], code: "DK" },
  { country: "Djibouti", languages: ["French", "Arabic"], code: "DJ" },
  { country: "Dominica", languages: ["English"], code: "DM" },
  { country: "Dominican Republic", languages: ["Spanish"], code: "DO" },
  { country: "Ecuador", languages: ["Spanish"], code: "EC" },
  { country: "Egypt", languages: ["Arabic"], code: "EG" },
  { country: "El Salvador", languages: ["Spanish"], code: "SV" },
  { country: "Equatorial Guinea", languages: ["Spanish", "French", "Portuguese"], code: "GQ" },
  { country: "Eritrea", languages: ["Tigrinya", "Arabic", "English"], code: "ER" },
  { country: "Estonia", languages: ["Estonian"], code: "EE" },
  { country: "Eswatini", languages: ["Swazi", "English"], code: "SZ" },
  { country: "Ethiopia", languages: ["Amharic"], code: "ET" },
  { country: "Fiji", languages: ["English", "Fijian", "Hindi"], code: "FJ" },
  { country: "Finland", languages: ["Finnish", "Swedish"], code: "FI" },
  { country: "France", languages: ["French"], code: "FR" },
  { country: "Gabon", languages: ["French"], code: "GA" },
  { country: "Gambia", languages: ["English"], code: "GM" },
  { country: "Georgia", languages: ["Georgian"], code: "GE" },
  { country: "Germany", languages: ["German"], code: "DE" },
  { country: "Ghana", languages: ["English"], code: "GH" },
  { country: "Greece", languages: ["Greek"], code: "GR" },
  { country: "Grenada", languages: ["English"], code: "GD" },
  { country: "Guatemala", languages: ["Spanish"], code: "GT" },
  { country: "Guinea", languages: ["French"], code: "GN" },
  { country: "Guinea-Bissau", languages: ["Portuguese"], code: "GW" },
  { country: "Guyana", languages: ["English"], code: "GY" },
  { country: "Haiti", languages: ["Haitian Creole", "French"], code: "HT" },
  { country: "Honduras", languages: ["Spanish"], code: "HN" },
  { country: "Hungary", languages: ["Hungarian"], code: "HU" },
  { country: "Iceland", languages: ["Icelandic"], code: "IS" },
  { country: "India", languages: ["Hindi", "English"], code: "IN" },
  { country: "Indonesia", languages: ["Indonesian"], code: "ID" },
  { country: "Iran", languages: ["Persian"], code: "IR" },
  { country: "Iraq", languages: ["Arabic", "Kurdish"], code: "IQ" },
  { country: "Ireland", languages: ["Irish", "English"], code: "IE" },
  { country: "Israel", languages: ["Hebrew"], code: "IL" },
  { country: "Italy", languages: ["Italian"], code: "IT" },
  { country: "Jamaica", languages: ["English"], code: "JM" },
  { country: "Japan", languages: ["Japanese"], code: "JP" },
  { country: "Jordan", languages: ["Arabic"], code: "JO" },
  { country: "Kazakhstan", languages: ["Kazakh", "Russian"], code: "KZ" },
  { country: "Kenya", languages: ["Swahili", "English"], code: "KE" },
  { country: "Kiribati", languages: ["English"], code: "KI" },
  { country: "North Korea", languages: ["Korean"], code: "KP" },
  { country: "South Korea", languages: ["Korean"], code: "KR" },
  { country: "Kuwait", languages: ["Arabic"], code: "KW" },
  { country: "Kyrgyzstan", languages: ["Kyrgyz", "Russian"], code: "KG" },
  { country: "Laos", languages: ["Lao"], code: "LA" },
  { country: "Latvia", languages: ["Latvian"], code: "LV" },
  { country: "Lebanon", languages: ["Arabic"], code: "LB" },
  { country: "Lesotho", languages: ["Sesotho", "English"], code: "LS" },
  { country: "Liberia", languages: ["English"], code: "LR" },
  { country: "Libya", languages: ["Arabic"], code: "LY" },
  { country: "Liechtenstein", languages: ["German"], code: "LI" },
  { country: "Lithuania", languages: ["Lithuanian"], code: "LT" },
  { country: "Luxembourg", languages: ["Luxembourgish", "French", "German"], code: "LU" },
  { country: "Madagascar", languages: ["Malagasy", "French"], code: "MG" },
  { country: "Malawi", languages: ["English"], code: "MW" },
  { country: "Malaysia", languages: ["Malay"], code: "MY" },
  { country: "Maldives", languages: ["Dhivehi"], code: "MV" },
  { country: "Mali", languages: ["French"], code: "ML" },
  { country: "Malta", languages: ["Maltese", "English"], code: "MT" },
  { country: "Marshall Islands", languages: ["Marshallese", "English"], code: "MH" },
  { country: "Mauritania", languages: ["Arabic"], code: "MR" },
  { country: "Mauritius", languages: ["English"], code: "MU" },
  { country: "Mexico", languages: ["Spanish"], code: "MX" },
  { country: "Micronesia", languages: ["English"], code: "FM" },
  { country: "Moldova", languages: ["Romanian"], code: "MD" },
  { country: "Monaco", languages: ["French"], code: "MC" },
  { country: "Mongolia", languages: ["Mongolian"], code: "MN" },
  { country: "Montenegro", languages: ["Montenegrin"], code: "ME" },
  { country: "Morocco", languages: ["Arabic"], code: "MA" },
  { country: "Mozambique", languages: ["Portuguese"], code: "MZ" },
  { country: "Myanmar", languages: ["Burmese"], code: "MM" },
  { country: "Namibia", languages: ["English"], code: "NA" },
  { country: "Nauru", languages: ["Nauruan", "English"], code: "NR" },
  { country: "Nepal", languages: ["Nepali"], code: "NP" },
  { country: "Netherlands", languages: ["Dutch"], code: "NL" },
  { country: "New Zealand", languages: ["English", "Māori"], code: "NZ" },
  { country: "Nicaragua", languages: ["Spanish"], code: "NI" },
  { country: "Niger", languages: ["French"], code: "NE" },
  { country: "Nigeria", languages: ["English"], code: "NG" },
  { country: "North Macedonia", languages: ["Macedonian"], code: "MK" },
  { country: "Norway", languages: ["Norwegian"], code: "NO" },
  { country: "Oman", languages: ["Arabic"], code: "OM" },
  { country: "Pakistan", languages: ["Urdu"], code: "PK" },
  { country: "Palau", languages: ["Palauan", "English"], code: "PW" },
  { country: "Palestine", languages: ["Arabic"], code: "PS" },
  { country: "Panama", languages: ["Spanish"], code: "PA" },
  { country: "Papua New Guinea", languages: ["Tok Pisin", "English", "Hiri Motu"], code: "PG" },
  { country: "Paraguay", languages: ["Spanish", "Guarani"], code: "PY" },
  { country: "Peru", languages: ["Spanish"], code: "PE" },
  { country: "Philippines", languages: ["Filipino", "English"], code: "PH" },
  { country: "Poland", languages: ["Polish"], code: "PL" },
  { country: "Portugal", languages: ["Portuguese"], code: "PT" },
  { country: "Qatar", languages: ["Arabic"], code: "QA" },
  { country: "Romania", languages: ["Romanian"], code: "RO" },
  { country: "Russia", languages: ["Russian"], code: "RU" },
  { country: "Rwanda", languages: ["Kinyarwanda", "English", "French"], code: "RW" },
  { country: "Saint Kitts and Nevis", languages: ["English"], code: "KN" },
  { country: "Saint Lucia", languages: ["English"], code: "LC" },
  { country: "Saint Vincent and the Grenadines", languages: ["English"], code: "VC" },
  { country: "Samoa", languages: ["Samoan", "English"], code: "WS" },
  { country: "San Marino", languages: ["Italian"], code: "SM" },
  { country: "Sao Tome and Principe", languages: ["Portuguese"], code: "ST" },
  { country: "Saudi Arabia", languages: ["Arabic"], code: "SA" },
  { country: "Senegal", languages: ["French"], code: "SN" },
  { country: "Serbia", languages: ["Serbian"], code: "RS" },
  { country: "Seychelles", languages: ["Seychellois Creole", "English", "French"], code: "SC" },
  { country: "Sierra Leone", languages: ["English"], code: "SL" },
  { country: "Singapore", languages: ["English", "Malay", "Mandarin", "Tamil"], code: "SG" },
  { country: "Slovakia", languages: ["Slovak"], code: "SK" },
  { country: "Slovenia", languages: ["Slovene"], code: "SI" },
  { country: "Solomon Islands", languages: ["English"], code: "SB" },
  { country: "Somalia", languages: ["Somali", "Arabic"], code: "SO" },
  { country: "South Africa", languages: ["Zulu", "Xhosa", "Afrikaans", "English"], code: "ZA" },
  { country: "South Sudan", languages: ["English"], code: "SS" },
  { country: "Spain", languages: ["Spanish"], code: "ES" },
  { country: "Sri Lanka", languages: ["Sinhala", "Tamil"], code: "LK" },
  { country: "Sudan", languages: ["Arabic", "English"], code: "SD" },
  { country: "Suriname", languages: ["Dutch"], code: "SR" },
  { country: "Sweden", languages: ["Swedish"], code: "SE" },
  { country: "Switzerland", languages: ["German", "French", "Italian"], code: "CH" },
  { country: "Syria", languages: ["Arabic"], code: "SY" },
  { country: "Tajikistan", languages: ["Tajik"], code: "TJ" },
  { country: "Tanzania", languages: ["Swahili", "English"], code: "TZ" },
  { country: "Thailand", languages: ["Thai"], code: "TH" },
  { country: "Timor-Leste", languages: ["Tetum", "Portuguese"], code: "TL" },
  { country: "Togo", languages: ["French"], code: "TG" },
  { country: "Tonga", languages: ["Tongan", "English"], code: "TO" },
  { country: "Trinidad and Tobago", languages: ["English"], code: "TT" },
  { country: "Tunisia", languages: ["Arabic"], code: "TN" },
  { country: "Turkey", languages: ["Turkish"], code: "TR" },
  { country: "Turkmenistan", languages: ["Turkmen"], code: "TM" },
  { country: "Tuvalu", languages: ["Tuvaluan", "English"], code: "TV" },
  { country: "Uganda", languages: ["English"], code: "UG" },
  { country: "Ukraine", languages: ["Ukrainian"], code: "UK" },
  { country: "United Arab Emirates", languages: ["Arabic"], code: "AE" },
  { country: "United Kingdom", languages: ["English"], code: "GB" },
  { country: "United States", languages: ["English"], code: "US" },
  { country: "Uruguay", languages: ["Spanish"], code: "UY" },
  { country: "Uzbekistan", languages: ["Uzbek"], code: "UZ" },
  { country: "Vanuatu", languages: ["Bislama", "English", "French"], code: "VU" },
  { country: "Vatican City", languages: ["Italian", "Latin"], code: "VA" },
  { country: "Venezuela", languages: ["Spanish"], code: "VE" },
  { country: "Vietnam", languages: ["Vietnamese"], code: "VN" },
  { country: "Yemen", languages: ["Arabic"], code: "YE" },
  { country: "Zambia", languages: ["English"], code: "ZM" },
  { country: "Zimbabwe", languages: ["English", "Shona", "Ndebele"], code: "ZW" },
];
